name: Deploy hugo site via github actions
on:
  push:
    branches:
      - gh-pages
  pull_request:

env: 
  URL_DEV: phamjust.github.io
  URL_PRO: justinpham.info

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  Deploy-dev-env:
    name: Deploy to phamjust.github.io
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: gh-pages
          submodule: true #fetch hugo themes (true or recursive)
          fetch-depth: 0 #fetch all history for .GetInfo and .Lastmod

      - name: Setup hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'

      - name: Build
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
